localhost:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=eltonokawa
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=onboard

test:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=eltonokawa
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=onboard-test
